#!/usr/bin/env python3
"""Install, validate, and inspect the hardened Ralph runtime."""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any


SKILL_ROOT = Path(__file__).resolve().parent.parent
RUNTIME_ROOT = SKILL_ROOT / "assets" / "runtime"
MANAGED_RUNTIME_FILES = (
    "VERSION",
    "loop.sh",
    "status.sh",
    "format-codex-stream.py",
    "format-stream.py",
    "pretty-process-snapshots.py",
    "lib/ralph-common.sh",
    "hooks/post-sprint.sh",
    "hooks/review.sh",
    "hooks/document.sh",
    "hooks/test.sh",
    "prompts/review.md",
    "prompts/document.md",
    "prompts/test.md",
)
AGENTS = {"amp", "claude", "codex", "droid", "opencode", "custom"}


class RalphError(ValueError):
    pass


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def runtime_version() -> str:
    return (RUNTIME_ROOT / "VERSION").read_text(encoding="utf-8").strip()


def shell_value(value: str) -> str:
    if not value:
        return ""
    return "'" + value.replace("'", "'\"'\"'") + "'"


def render_config(arguments: argparse.Namespace) -> str:
    values: dict[str, str] = {}
    for raw in (
        (RUNTIME_ROOT / "config.env.template").read_text(encoding="utf-8").splitlines()
    ):
        if raw and not raw.startswith("#") and "=" in raw:
            key, value = raw.split("=", 1)
            values[key] = value
    values.update(
        {
            "RALPH_AGENT": arguments.agent,
            "RALPH_AGENT_COMMAND": shell_value(arguments.agent_command or ""),
            "RALPH_UNATTENDED_APPROVED": "true"
            if arguments.approve_unattended
            else "false",
            "RALPH_TEST_COMMAND": shell_value(arguments.test_command or ""),
            "RALPH_E2E_COMMAND": shell_value(arguments.e2e_command or ""),
            "RALPH_REVIEW_ENABLED": "false" if arguments.disable_review else "true",
            "RALPH_DOCUMENTATION_ENABLED": "false"
            if arguments.disable_documentation
            else "true",
            "RALPH_TESTS_ENABLED": "false" if arguments.disable_tests else "true",
        }
    )
    lines = [
        "# Generated by the ralph-workflows skill. This file is sourced by Bash; treat it as trusted code."
    ]
    lines.extend(f"{key}={value}" for key, value in values.items())
    return "\n".join(lines) + "\n"


def copy_runtime(target: Path) -> dict[str, str]:
    checksums: dict[str, str] = {}
    resolved_target = target.resolve()
    for relative in MANAGED_RUNTIME_FILES:
        destination = target / relative
        if destination.is_symlink():
            raise RalphError(f"Refusing to replace managed symlink: {destination}")
        if not destination.parent.resolve().is_relative_to(resolved_target):
            raise RalphError(f"Refusing managed path outside runtime: {destination}")
    for relative in MANAGED_RUNTIME_FILES:
        source = RUNTIME_ROOT / relative
        destination = target / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
        checksums[relative] = sha256(destination)
    return checksums


def write_json(path: Path, value: dict[str, Any]) -> None:
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(
        json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    temporary.replace(path)


def install(arguments: argparse.Namespace) -> Path:
    repo = arguments.repo.resolve()
    if not (repo / ".git").exists():
        raise RalphError(f"Not a Git repository root: {repo}")
    target = repo / ".ralph"
    config = target / "config.env"
    metadata_path = target / ".runtime-manifest.json"
    if target.is_symlink():
        raise RalphError(f"Refusing symlinked runtime directory: {target}")
    if target.exists() and not arguments.update_runtime:
        raise RalphError(
            f"Refusing to overwrite existing runtime: {target}; use --update-runtime"
        )

    target.mkdir(parents=True, exist_ok=True)
    if config.is_symlink():
        raise RalphError(f"Refusing symlinked runtime configuration: {config}")
    checksums = copy_runtime(target)
    if not config.exists():
        config.write_text(render_config(arguments), encoding="utf-8")
    elif not arguments.update_runtime:
        raise RalphError(f"Refusing to overwrite existing config: {config}")

    previous: dict[str, Any] = {}
    if metadata_path.exists():
        try:
            previous = json.loads(metadata_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            previous = {}
    write_json(
        metadata_path,
        {
            "schema_version": "1.0",
            "runtime_version": runtime_version(),
            "managed_files": checksums,
            "previous_runtime_version": previous.get("runtime_version"),
        },
    )
    (target / "sprints").mkdir(exist_ok=True)
    (target / "logs").mkdir(exist_ok=True)
    return target


def parse_config(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line_number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise RalphError(f"config.env:{line_number} is not KEY=VALUE")
        key, value = line.split("=", 1)
        values[key] = value.strip().strip("'\"")
    return values


def validate_sprint(path: Path) -> list[dict[str, str]]:
    findings: list[dict[str, str]] = []
    required = (
        "README.md",
        "IMPLEMENTATION_PLAN.md",
        "relevant-specs.md",
        "chunks.json",
        "prompt.md",
        "SCRATCHPAD.md",
    )
    for name in required:
        if not (path / name).is_file():
            findings.append(
                {
                    "status": "fail",
                    "check": f"sprint:{path.name}:{name}",
                    "detail": "missing",
                }
            )
    chunks_path = path / "chunks.json"
    if chunks_path.exists():
        try:
            payload = json.loads(chunks_path.read_text(encoding="utf-8"))
            chunks = payload.get("chunks")
            if not isinstance(chunks, list) or not chunks:
                raise RalphError("chunks must be a non-empty array")
            ids = [chunk.get("id") for chunk in chunks if isinstance(chunk, dict)]
            if ids != list(range(1, len(chunks) + 1)):
                raise RalphError("chunk IDs must be sequential integers starting at 1")
            for chunk in chunks:
                if not isinstance(chunk.get("passes"), bool):
                    raise RalphError(f"chunk {chunk.get('id')} passes must be boolean")
                for field in ("acceptance_criteria", "artifacts"):
                    if not isinstance(chunk.get(field), list):
                        raise RalphError(
                            f"chunk {chunk.get('id')} {field} must be an array"
                        )
            findings.append(
                {
                    "status": "pass",
                    "check": f"sprint:{path.name}:chunks",
                    "detail": f"{len(chunks)} sequential chunks",
                }
            )
        except (json.JSONDecodeError, RalphError) as error:
            findings.append(
                {
                    "status": "fail",
                    "check": f"sprint:{path.name}:chunks",
                    "detail": str(error),
                }
            )
    prompt_path = path / "prompt.md"
    if prompt_path.exists():
        prompt = prompt_path.read_text(encoding="utf-8")
        for token in ("SCRATCHPAD.md", "RALPH_CHUNK_COMPLETE"):
            if token not in prompt:
                findings.append(
                    {
                        "status": "fail",
                        "check": f"sprint:{path.name}:prompt",
                        "detail": f"missing {token}",
                    }
                )
    return findings


def validate(repo: Path) -> dict[str, Any]:
    root = repo.resolve() / ".ralph"
    findings: list[dict[str, str]] = []
    for command in ("bash", "git", "jq", "python3"):
        executable = shutil.which(command)
        findings.append(
            {
                "status": "pass" if executable else "fail",
                "check": f"prerequisite:{command}",
                "detail": executable or "not found on PATH",
            }
        )
    for relative in MANAGED_RUNTIME_FILES:
        path = root / relative
        findings.append(
            {
                "status": "pass" if path.is_file() else "fail",
                "check": f"runtime:{relative}",
                "detail": "present" if path.is_file() else "missing",
            }
        )
    metadata_path = root / ".runtime-manifest.json"
    if metadata_path.is_file():
        try:
            metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
            expected = metadata.get("managed_files", {})
            drift = [
                relative
                for relative, checksum in expected.items()
                if not (root / relative).is_file()
                or sha256(root / relative) != checksum
            ]
            findings.append(
                {
                    "status": "fail" if drift else "pass",
                    "check": "runtime:fingerprint",
                    "detail": "drift: " + ", ".join(drift)
                    if drift
                    else "managed runtime matches installation manifest",
                }
            )
        except (json.JSONDecodeError, OSError) as error:
            findings.append(
                {"status": "fail", "check": "runtime:fingerprint", "detail": str(error)}
            )
    else:
        findings.append(
            {
                "status": "warn",
                "check": "runtime:fingerprint",
                "detail": "installation manifest missing",
            }
        )
    config_path = root / "config.env"
    if not config_path.is_file():
        findings.append(
            {"status": "fail", "check": "config", "detail": "missing .ralph/config.env"}
        )
        config: dict[str, str] = {}
    else:
        try:
            config = parse_config(config_path)
            findings.append(
                {
                    "status": "pass",
                    "check": "config",
                    "detail": "parseable KEY=VALUE configuration",
                }
            )
        except RalphError as error:
            config = {}
            findings.append({"status": "fail", "check": "config", "detail": str(error)})
    agent = config.get("RALPH_AGENT", "")
    if agent not in AGENTS:
        findings.append(
            {
                "status": "fail",
                "check": "agent",
                "detail": f"unsupported RALPH_AGENT={agent or 'missing'}",
            }
        )
    elif agent == "custom" and not config.get("RALPH_AGENT_COMMAND"):
        findings.append(
            {
                "status": "fail",
                "check": "agent",
                "detail": "custom agent requires RALPH_AGENT_COMMAND",
            }
        )
    else:
        executable = config.get("RALPH_AGENT_COMMAND") or shutil.which(agent)
        findings.append(
            {
                "status": "pass" if executable else "fail",
                "check": "agent",
                "detail": agent
                if executable
                else f"{agent} executable not found on PATH",
            }
        )
    if config.get("RALPH_UNATTENDED_APPROVED") != "true":
        findings.append(
            {
                "status": "warn",
                "check": "authorization",
                "detail": "runtime is safely disarmed",
            }
        )
    if config.get("RALPH_TESTS_ENABLED", "true") == "true" and not config.get(
        "RALPH_TEST_COMMAND"
    ):
        findings.append(
            {
                "status": "fail",
                "check": "tests",
                "detail": "enabled but RALPH_TEST_COMMAND is empty",
            }
        )
    sprints = root / "sprints"
    if sprints.is_dir():
        sprint_paths = sorted(path for path in sprints.iterdir() if path.is_dir())
        current_sprint = config.get("CURRENT_SPRINT", "")
        if sprint_paths and not current_sprint:
            findings.append(
                {
                    "status": "fail",
                    "check": "current-sprint",
                    "detail": "CURRENT_SPRINT is empty",
                }
            )
        elif current_sprint and not (sprints / current_sprint).is_dir():
            findings.append(
                {
                    "status": "fail",
                    "check": "current-sprint",
                    "detail": f"sprint directory not found: {current_sprint}",
                }
            )
        elif current_sprint:
            findings.append(
                {"status": "pass", "check": "current-sprint", "detail": current_sprint}
            )
        for sprint in sprint_paths:
            findings.extend(validate_sprint(sprint))
    failed = sum(item["status"] == "fail" for item in findings)
    warned = sum(item["status"] == "warn" for item in findings)
    return {
        "ok": failed == 0,
        "failed": failed,
        "warnings": warned,
        "findings": findings,
    }


def print_validation(report: dict[str, Any], as_json: bool) -> None:
    if as_json:
        print(json.dumps(report, indent=2))
        return
    for item in report["findings"]:
        print(f"{item['status'].upper():4}  {item['check']}: {item['detail']}")
    print(f"Summary: {report['failed']} failed, {report['warnings']} warnings")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    init_parser = subparsers.add_parser(
        "init", help="Install the runtime without overwriting sprint state."
    )
    init_parser.add_argument("--repo", type=Path, default=Path.cwd())
    init_parser.add_argument("--agent", choices=sorted(AGENTS), default="codex")
    init_parser.add_argument(
        "--agent-command",
        help="Trusted custom shell command; receives RALPH_PROMPT_FILE and RALPH_PROJECT_ROOT.",
    )
    init_parser.add_argument("--test-command")
    init_parser.add_argument("--e2e-command")
    init_parser.add_argument("--approve-unattended", action="store_true")
    init_parser.add_argument("--disable-review", action="store_true")
    init_parser.add_argument("--disable-documentation", action="store_true")
    init_parser.add_argument("--disable-tests", action="store_true")
    init_parser.add_argument("--update-runtime", action="store_true")
    validate_parser = subparsers.add_parser(
        "validate", help="Validate runtime, configuration, and sprints."
    )
    validate_parser.add_argument("--repo", type=Path, default=Path.cwd())
    validate_parser.add_argument("--json", action="store_true")
    status_parser = subparsers.add_parser(
        "status", help="Run the installed runtime status command."
    )
    status_parser.add_argument("--repo", type=Path, default=Path.cwd())
    status_parser.add_argument("--sprint")
    return parser


def main() -> int:
    arguments = build_parser().parse_args()
    try:
        if arguments.command == "init":
            target = install(arguments)
            print(f"Installed Ralph runtime {runtime_version()}: {target}")
            if arguments.approve_unattended:
                print(
                    "Unattended execution was explicitly approved for this generated configuration."
                )
            else:
                print("Runtime remains disarmed until RALPH_UNATTENDED_APPROVED=true.")
            return 0
        if arguments.command == "validate":
            report = validate(arguments.repo)
            print_validation(report, arguments.json)
            return 0 if report["ok"] else 1
        status = arguments.repo.resolve() / ".ralph" / "status.sh"
        if not status.is_file():
            raise RalphError(f"Runtime not found: {status}")
        command = [str(status)]
        if arguments.sprint:
            command.append(arguments.sprint)
        return subprocess.run(
            command, cwd=arguments.repo.resolve(), check=False
        ).returncode
    except (OSError, RalphError) as error:
        print(str(error), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
